### ISSUE TITLE
workspace.list_variables may raise TypeError

### ISSUE THREAD

**Issue by arthur78** [trakken/gtm_manager#4]
I was iterating through containers in an account and listing variables in their default workspaces. For one of the containers, I got the exception below. I went to the GTM UI and manually checked that container: it has several built-in variables and no user-defined variables. 

My assumption is that the `list_variables` method should not raise. Can you please check?

```
...
  File "/Users/xak/dev/.virtualenvs/gtm/lib/python3.6/site-packages/gtm_manager/workspace.py", line 385, in list_variables
    for x in response.get("variable")
TypeError: 'NoneType' object is not iterable
```

**Comment by hrisp** [comment]
Hey @arthur78 
Thank you very much for opening the issue and sharing your feedback! 

I improved the list methods to handle empty lists and added a bunch more tests. It's all available in v0.2.5. I would be delighted if you would give it another try :)

Thanks
Chris
